<div style="float:left; padding-right:16px;"></div>
<h3><?php echo $this->translate('Witaj administratorze'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<div class="jumbotron">
     <p><a class="btn btn-success btn-lg center-block" href="/zamowienia/indexr" target="_self"><?php echo $this->translate('Zarządzaj zamówieniami') ?> &raquo;</a></p>
     <p><a class="btn btn-success btn-lg center-block" href="/zamowienia/add" target="_self"><?php echo $this->translate('Dodaj zamówienie') ?> &raquo;</a></p>
     <p><a class="btn btn-success btn-lg center-block" href="/uzytkownicy" target="_self"><?php echo $this->translate('Zarządzaj użytkownikami') ?> &raquo;</a></p>     
</div>
<div style="clear:both;"></div>
