<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Składzik '. $this->translate('Zamojskiego Stowarzyszenia Kulturalnego \'Czerwony Smok\''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/cslogo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('ZSK "Czerwony Smok"') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><span class="glyphicon glyphicon-home"><?php echo $this->translate(' Strona główna') ?></a></li>
                        <li class="active"><a href="/skladzik"><span class="glyphicon glyphicon-inbox"><?php echo $this->translate(' Składzik') ?></a></li>                        
                        
                        <li class="active"><a href="/zamowienia"><span class="glyphicon glyphicon-book"><?php echo $this->translate(' Twoje zamówienia') ?></a></li>
                        
                        
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <btn-group>
                            <a href="/user/login"  role="button" class="btn btn-success navbar-btn">
                                        <span class="glyphicon glyphicon-user"> Użytkownik</span>
                            </a>
                            <a href="/zamowienia/indexadmin"  role="button" class="btn btn-danger navbar-btn">
                                        <span class="glyphicon glyphicon-wrench"> Administracja</span>
                            </a>
                        </btn-group>
   
                    </ul>
                    
                        
                    
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
